# Generated by Django 4.1 on 2022-08-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
    ]
