# Generated by Django 4.1 on 2022-08-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_name_alter_category_parentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.season')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
    ]
