# Generated by Django 4.1 on 2022-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_season_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Producers',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='producer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
